// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmpquunngmpbbocewhvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtcHF1dW5uZ21wYmJvY2V3aHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjA0NzYsImV4cCI6MjA2NjU5NjQ3Nn0.KdwhDUwMalx7x60zkaWG2dVsSFtj3SRoOqkSsqFJCsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);